// <auto-generated />
using EasyGrade.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EasyGrade.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515214415_AddStoredConflitos")]
    partial class AddStoredConflitos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EasyGrade.Domain.Entities.Aula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dia");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hora");

                    b.Property<int?>("MateriaId")
                        .HasColumnType("integer")
                        .HasColumnName("materia_id");

                    b.Property<int?>("ProfessorId")
                        .HasColumnType("integer")
                        .HasColumnName("professor_id");

                    b.Property<int?>("SalaId")
                        .HasColumnType("integer")
                        .HasColumnName("sala_id");

                    b.Property<int>("SemestreId")
                        .HasColumnType("integer")
                        .HasColumnName("semestre_id");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("SalaId");

                    b.HasIndex("SemestreId");

                    b.ToTable("aulas", (string)null);
                });

            modelBuilder.Entity("EasyGrade.Domain.Entities.Conflito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AulaConflitanteId")
                        .HasColumnType("integer")
                        .HasColumnName("aula_conflitante_id");

                    b.Property<int>("AulaId")
                        .HasColumnType("integer")
                        .HasColumnName("aula_id");

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("dia");

                    b.Property<int>("GradeId")
                        .HasColumnType("integer")
                        .HasColumnName("grade_id");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("hora");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("AulaConflitanteId");

                    b.HasIndex("AulaId");

                    b.HasIndex("GradeId");

                    b.HasIndex("GradeId", "AulaId", "AulaConflitanteId", "Tipo")
                        .IsUnique();

                    b.ToTable("conflitos", (string)null);
                });

            modelBuilder.Entity("EasyGrade.Domain.Entities.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("cursos", (string)null);
                });

            modelBuilder.Entity("EasyGrade.Domain.Entities.Eixo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("eixos", (string)null);
                });

            modelBuilder.Entity("EasyGrade.Domain.Entities.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("grades", (string)null);
                });

            modelBuilder.Entity("EasyGrade.Domain.Entities.GradeCurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CursoId")
                        .HasColumnType("integer")
                        .HasColumnName("curso_id");

                    b.Property<int>("GradeEixoId")
                        .HasColumnType("integer")
                        .HasColumnName("grade_eixo_id");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("GradeEixoId");

                    b.ToTable("grade_cursos", (string)null);
                });

            modelBuilder.Entity("EasyGrade.Domain.Entities.GradeEixo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EixoId")
                        .HasColumnType("integer")
                        .HasColumnName("eixo_id");

                    b.Property<int>("GradeId")
                        .HasColumnType("integer")
                        .HasColumnName("grade_id");

                    b.HasKey("Id");

                    b.HasIndex("EixoId");

                    b.HasIndex("GradeId");

                    b.ToTable("grade_eixos", (string)null);
                });

            modelBuilder.Entity("EasyGrade.Domain.Entities.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("materias", (string)null);
                });

            modelBuilder.Entity("EasyGrade.Domain.Entities.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("professores", (string)null);
                });

            modelBuilder.Entity("EasyGrade.Domain.Entities.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("salas", (string)null);
                });

            modelBuilder.Entity("EasyGrade.Domain.Entities.Semestre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GradeCursoId")
                        .HasColumnType("integer")
                        .HasColumnName("grade_curso_id");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.HasKey("Id");

                    b.HasIndex("GradeCursoId");

                    b.ToTable("semestres", (string)null);
                });

            modelBuilder.Entity("EasyGrade.Domain.Entities.Aula", b =>
                {
                    b.HasOne("EasyGrade.Domain.Entities.Materia", "Materia")
                        .WithMany("Aulas")
                        .HasForeignKey("MateriaId");

                    b.HasOne("EasyGrade.Domain.Entities.Professor", "Professor")
                        .WithMany("Aulas")
                        .HasForeignKey("ProfessorId");

                    b.HasOne("EasyGrade.Domain.Entities.Sala", "Sala")
                        .WithMany("Aulas")
                        .HasForeignKey("SalaId");

                    b.HasOne("EasyGrade.Domain.Entities.Semestre", "Semestre")
                        .WithMany("Aulas")
                        .HasForeignKey("SemestreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("Professor");

                    b.Navigation("Sala");

                    b.Navigation("Semestre");
                });

            modelBuilder.Entity("EasyGrade.Domain.Entities.Conflito", b =>
                {
                    b.HasOne("EasyGrade.Domain.Entities.Aula", "AulaConflitante")
                        .WithMany()
                        .HasForeignKey("AulaConflitanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyGrade.Domain.Entities.Aula", "Aula")
                        .WithMany()
                        .HasForeignKey("AulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyGrade.Domain.Entities.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aula");

                    b.Navigation("AulaConflitante");

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("EasyGrade.Domain.Entities.GradeCurso", b =>
                {
                    b.HasOne("EasyGrade.Domain.Entities.Curso", "Curso")
                        .WithMany("GradeCursos")
                        .HasForeignKey("CursoId");

                    b.HasOne("EasyGrade.Domain.Entities.GradeEixo", "GradeEixo")
                        .WithMany("Cursos")
                        .HasForeignKey("GradeEixoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("GradeEixo");
                });

            modelBuilder.Entity("EasyGrade.Domain.Entities.GradeEixo", b =>
                {
                    b.HasOne("EasyGrade.Domain.Entities.Eixo", "Eixo")
                        .WithMany()
                        .HasForeignKey("EixoId");

                    b.HasOne("EasyGrade.Domain.Entities.Grade", "Grade")
                        .WithMany("Eixos")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eixo");

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("EasyGrade.Domain.Entities.Semestre", b =>
                {
                    b.HasOne("EasyGrade.Domain.Entities.GradeCurso", "GradeCurso")
                        .WithMany("Semestres")
                        .HasForeignKey("GradeCursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradeCurso");
                });

            modelBuilder.Entity("EasyGrade.Domain.Entities.Curso", b =>
                {
                    b.Navigation("GradeCursos");
                });

            modelBuilder.Entity("EasyGrade.Domain.Entities.Grade", b =>
                {
                    b.Navigation("Eixos");
                });

            modelBuilder.Entity("EasyGrade.Domain.Entities.GradeCurso", b =>
                {
                    b.Navigation("Semestres");
                });

            modelBuilder.Entity("EasyGrade.Domain.Entities.GradeEixo", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("EasyGrade.Domain.Entities.Materia", b =>
                {
                    b.Navigation("Aulas");
                });

            modelBuilder.Entity("EasyGrade.Domain.Entities.Professor", b =>
                {
                    b.Navigation("Aulas");
                });

            modelBuilder.Entity("EasyGrade.Domain.Entities.Sala", b =>
                {
                    b.Navigation("Aulas");
                });

            modelBuilder.Entity("EasyGrade.Domain.Entities.Semestre", b =>
                {
                    b.Navigation("Aulas");
                });
#pragma warning restore 612, 618
        }
    }
}
